language: node_js

sudo: false

node_js:
  - "5.0"
  - "4.0"
  - 'iojs'
  - '0.12'
  - '0.10'

cache:
  directories:
    - node_modules

script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js || true"
